### ISSUE TITLE
Times in ranges - in percentages or in minutes?

### ISSUE THREAD

**Issue by mrinnetmaki** [argonautproject/cgm#1]
The [current proposal for times in ranges](https://build.fhir.org/ig/argonautproject/cgm/StructureDefinition-cgm-summary-times-in-ranges.html#profile) sets the unit to percentages.

This seems to fit the [latest (v. 5.0) AGP report](http://www.agpreport.org/agp/agpreports) definition.

However, if you read the textual description, it says:

> For people with diabetes, this table shows the goal in both % of device readings **and in hours/minutes of a 24 hours day** that are the targets (closer to these is better)

The previous version of the AGP report displayed also the minutes in the report (see [https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7801761/](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7801761/) for a reference).

A usual day has 1440 minutes. So, it is not possible to get from the (integer) percent value to minute level granularity. To the other direction (expressing the minutes, and then calculating the percentage), lossless transformation is possible.

Not sure whether I'm being overly strict here, and whether minute level accuracy is clinically relevant. Just pointing out that if you'd like to support AGP report v. 4.0, you might not be able to do that exactly, based on the percentage values alone.

I don't have a suggestion for a change yet. We might want to just say that percentages with decimals are OK (and encouraged?) for data transfer purposes, and the client should still present the values as integers. Or we could use minutes as the unit. Or a rate (readings in the range per total number of readings). Or just keep the current proposal.

**Comment by jmandel** [comment]
Josh: Short-term decision: we'll document % and recommend up to two decimal places of precision so that the numbers can be converted to "minutes of a typical day" without having more than 1min error

**Comment by jmandel** [comment]
Addressed in https://github.com/HL7/cgm/commit/2d02cb7b25538f9df0b63fe12d19767905e765bb
