### ISSUE TITLE
The serial number of the CGM may be challenging to support

### ISSUE THREAD

**Issue by mrinnetmaki** [argonautproject/cgm#2]
The [current version of the CGM Device](https://github.com/argonautproject/cgm/blob/main/input/fsh/profiles.fsh#L269) sets the minimum cardinality of the serial number to 1.

There are two issues.

1) The profile is not explicit on whether it refers to the actual sensor (that is attached to skin), or the reader device that gets the values from the sensor (this may be a dedicated hardware device, or a mobile app).
 
2) We have seen some APIs (and also export formats) where the serial number of the sensor is not available. It may still be useful to include some information of the used sensor (to indicate which readings in a bundle originate from one sensor, which ones from another, even if you are not able to identify the sensor with the serial number). It is also not that clear what the serial number would be if the device refers to the reader device and the reader device is a mobile app.

**Comment by jmandel** [comment]
1. Device corresponds to sensor, not reader/app. We'll clarify this, thank you!

2. Then re: serial number, from discussion on today's call the plan will be:

* Keep `.identifier` as 1..* to allow EHRs to recognize duplicate data arriving. Some stable identifier but not necessarily a serial number
* Change `serialNumber` to 0..1 (optional aligns with icode "expanded" data set recommendations)
* Continue to require a `deviceName`, and be clear that this includes manufacturer + model

**Comment by jmandel** [comment]
Fixed in https://github.com/HL7/cgm/commit/7b6fb3799329c9185ff3f44a23686b42c943559a
